### ISSUE TITLE
BlackboxFunction interface implementation missing for ZDT1

### ISSUE THREAD

**Issue by SebastianMortag** [nicolaipalm/paref#5]
https://github.com/nicolaipalm/paref/blob/c7293dba2cd4d5b9c61ba19c77e1a93204a7adca/examples/blackbox_functions/two_dimensional/zdt1.py#L8-L8

The ZDT1 class doesn't implement the BlackboxFunction Interface functions.

**Comment by nicolaipalm** [comment]
ZDT1 is now implemented into the BlackboxFunction interface.
