### ISSUE TITLE
Evaluations cutoff leads to wrong results in example notebook

### ISSUE THREAD

**Issue by SebastianMortag** [nicolaipalm/paref#6]
https://github.com/nicolaipalm/paref/blob/c7293dba2cd4d5b9c61ba19c77e1a93204a7adca/paref/moo_algorithms/minimizer/differential_evolution_minimizer.py#L28-L29

Shrinking the evaluations list in DifferentialEvolutionMinimizer stops the example_notebook_small from executing completely.

**Comment by nicolaipalm** [comment]
I am not sure what the issue is here. Could you elaborate a bit more? Thanks!
