### ISSUE TITLE
Adjust epsilon in FindEdgePoints to continue to next point

### ISSUE THREAD

**Issue by RolandReitberger** [nicolaipalm/paref#8]
The FindEdgePoints function input "min_distance_to_evaluated_points" does not change the Pareto reflection convergence but only the distance to continue with another point in the same edge:
(moo_find_edge_points = FindEdgePoints(min_distance_to_evaluated_points=float))

The documentation seems unclear here. I am unsure if there is an option to set the epsilon for Paref to continue with the next edge point within the package functions.

Changing the _epsilon manually in the root files (paref.moo_algorithms.stopping_criteria.convergence_reached) achieves that. 
Manually changing it by setting moo_find_edge_points.sequence_of_pareto_reflections.stopping_criteria._epsilon = 1 did not help.
I think because _epsilon is not passed on to self.stopping_criteria = ConvergenceReached() in paref.pareto_reflection_sequences.multi_dimensional.find_edge_points_sequence.

**Comment by nicolaipalm** [comment]
The default for edge point search is now simply iterating through the edge point reflections until the stopping criteria is met. This should solve the issue. Thanks!
