### ISSUE TITLE
Bug in main example notebook

### ISSUE THREAD

**Issue by SebastianMortag** [nicolaipalm/paref#9]
`moo_find_edge_points(blackbox_function=bbf,
                     stopping_criteria=stopping_criteria)`
->
`    if np.any([np.all(dominated) for dominated in (gpr(res) >= blackbox_function.pareto_front)]):
ValueError: operands could not be broadcast together with shapes (2,) (0,)`
Main example notebook 
Possible cause:
Changes  to
paref/interfaces/moo_algorithms/paref_moo.py
in #168933ed1065c69d6d4c4a1eb167e1a630d21fbc  
resulting in  
`self._evaluations = [[evaluation[0], pareto_reflection(evaluation[1])] for evaluation in
                             blackbox_function._evaluations]`
doesn't calculate `_evaluations` properly.

**Comment by nicolaipalm** [comment]
This is now fixed in the new release 0.2.0
